services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: editor
    ports:
      - "5434:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
  app:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASS: postgres
      DB_NAME: editor
      JWT_SECRET: secret
      SALT_ROUNDS: 10
      NODE_ENV: development
      PORT: 3000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - temp-vol:/temp-vol
      - .:/app
    command: pnpm start:dev
volumes:
  db-data:
  temp-vol:
